# Generated by Django 5.0.2 on 2024-03-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habits',
            old_name='related_habbits',
            new_name='related_habits',
        ),
    ]
